default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: https://github.com/moreh-dev/pre-commit-hooks
    rev: v0.3.0
    hooks:
      - id: add-jira-issue-key-to-commit-msg
        args: ["--key", "MAF"]
